ktor:
    application:
        modules:
            - com.sm.ApplicationKt.module
    deployment:
        port: 9595
jwt:
  domain: "http://0.0.0.0:9595"
  audience: "jwt-audience"
  realm: "ktor-auth-app"
